### ISSUE TITLE
When calling the API for translation, sometimes it returns the original text to be translated, rather than the translated result.

### ISSUE THREAD

**Issue by YYyp99** [datpmt/google-translate-free-api#3]
This is the result after I called the API for translation.
<img width="484" alt="image" src="https://github.com/user-attachments/assets/e2c1fb4b-a98f-45e7-a8c8-ac548ee51489">

**Comment by datpmt** [comment]
Hi [YYyp99](https://github.com/YYyp99),

Could you provide more details about your implementation? Specifically, which API version are you using—v1 or v2? Additionally, could you let me know the value you're using for the to_lang parameter?

Thank you!

**Comment by YYyp99** [comment]
> Hi [YYyp99](https://github.com/YYyp99),
> 
> Could you provide more details about your implementation? Specifically, which API version are you using—v1 or v2? Additionally, could you let me know the value you're using for the to_lang parameter?
> 
> Thank you!

Initially, I was using v1, which worked normally. However, recently this issue has emerged. Then I noticed there was a v2, but v2 also experiences this same problem.
<img width="491" alt="image" src="https://github.com/user-attachments/assets/794fff41-644d-4bae-a7bd-a4e51f9cfadb">

**Comment by datpmt** [comment]
I’m currently using an alternative method in API `v1`. Please try it out and let me know the results after a few days of use. If it resolves your issue, let me know and kindly close this issue.

Thank you!

**Comment by YYyp99** [comment]
> I’m currently using an alternative method in API `v1`. Please try it out and let me know the results after a few days of use. If it resolves your issue, let me know and kindly close this issue.
> 
> Thank you!

Thank you very much. I just tried it, but it seems to have gotten even worse, haha.I am concatenating 100 words at a time into a string using line breaks, then translating it and splitting it back to refill. However, now it's only returning the first word of each batch.
<img width="390" alt="image" src="https://github.com/user-attachments/assets/6b701480-855f-4aa1-8f2b-18b5e1b2c51f">
<img width="382" alt="image" src="https://github.com/user-attachments/assets/e2184e2c-b070-4c02-a1ed-68e829e96028">

**Comment by datpmt** [comment]
I see, my new fix is not effective with `\n`.
I just have reverted it. I think I need more time to investigate and resolve the issue.

Do you think that the method of translating multiple different words at once by using line breaks is causing it to return the original text?

**Comment by datpmt** [comment]
> Do you think that the method of translating multiple different words at once by using line breaks is causing it to return the original text?

When you request text that contains multiple languages, it will detect the most frequently used language as `from_lang` and translate all words in that text according to the detected language. Therefore, you need to make sure that the text you send is in a single language

**Comment by YYyp99** [comment]
> > Do you think that the method of translating multiple different words at once by using line breaks is causing it to return the original text?
> 
> When you request text that contains multiple languages, it will detect the most frequently used language as `from_lang` and translate all words in that text according to the detected language. Therefore, you need to make sure that the text you send is in a single language

After my testing, it seems that we can't transmit very long paragraphs at once. I reduced the data from 100 lines to 50 lines, and now it appears to be working normally. Thank you very much!
<img width="400" alt="image" src="https://github.com/user-attachments/assets/c8bd9911-a0d0-44e8-ae88-e7d0a8867db5">
